#!/bin/csh -f
set cmd_dir=`dirname $0`

# Location of "mpipython"
set mpipython="/home/lugosi/users/ligocki/Software/Linux/bin/mpipython"

# Get rid of "--infile=..."
set new_argv=`echo "$argv" | sed -e 's/--infile=[^ ]*//g'`

# Get the number of processes to use
set nprocs=$new_argv[1]
set basename=$new_argv[2]

# Call the "Enumerate_Parallel_BSP.py" using "mpirun" and "mpipython"
mpirun -np $nprocs $mpipython $cmd_dir/Enumerate_Parallel_BSP.py $new_argv[3-]

/bin/rm $basename.out.check*
cat $basename.out.* | awk 'NF > 0 { print $0; }' > $basename.out
/bin/rm $basename.out.*
