#!/bin/csh -f
foreach i (Loops.*)
  echo $i
  if (-e $i/remain.0.bz2) then
    set catcmd=bzcat
    set ext=".bz2"
  else
    set catcmd=cat
    set ext=""
  endif
  echo -n "  0 "
  $catcmd $i/remain.0$ext | wc -l
  set foundsum=0
  foreach b (1 2 3 4 5 6)
    echo -n "  $b    "
    set found=`$catcmd $i/found.$b$ext | grep '^1' | wc -l`
    set foundsum=`expr $found + $foundsum`
    set remain=`$catcmd $i/remain.$b$ext | wc -l`
    set sum=`expr $remain + $foundsum`
    echo $remain $found $foundsum $sum
  end
end
