#!/bin/csh -f
set cmddir=`dirname $0`

set argc="$#argv"
if ("$argc" < 2) then
  echo "Usage: recur_some infile loops"
  exit 1
endif

set ll=`echo $2 | awk '{printf("%07d",$1);}'`

set file_base="$1:r"

/bin/cp $1 ${file_base}.$ll.0
wc -l ${file_base}.$ll.0

set lastn=0
foreach n (1 2 3 4 5 6)
  echo "--- $n ---"
  (time ${cmddir}/../Code/Recur_TM.py -n $n -b -p -l $2 ${file_base}.$ll.$lastn) > ${file_base}.recur.$ll.$n
  ${cmddir}/../Tools/cull_recur ${file_base}.$ll.$lastn ${file_base}.recur.$ll.$n > ${file_base}.$ll.$n
  wc -l ${file_base}.$ll.$n
  set lastn=$n
end
