#!/bin/csh -f
set cmddir=`dirname $0`

set argc="$#argv"
if ("$argc" < 1) then
  echo "Usage: recur_some loops"
  exit 1
endif

set ll=`echo $1 | awk '{printf("%07d",$1);}'`

if (! -e Loops.$ll) then
  mkdir Loops.$ll
endif

set loopdir=Loops.$ll

if (-e unknown.bz2) then
  bzcat unknown.bz2 > $loopdir/remain.0
else
  cat unknown > $loopdir/remain.0
endif
wc -l $loopdir/remain.0

set lastn=0
foreach n (1 2 3 4 5 6)
  echo "--- $n ---"
  (time ${cmddir}/../Code/Recur_TM.py -n $n -b -p -l $1 $loopdir/remain.$lastn) > $loopdir/recur.$n
  ${cmddir}/summary $loopdir/recur.$n > $loopdir/found.$n
  ${cmddir}/../Tools/cull_recur $loopdir/remain.$lastn $loopdir/recur.$n > $loopdir/remain.$n
  wc -l $loopdir/remain.$n
  set lastn=$n
end
