#!/bin/csh -f
####
#!/bin/csh -f
if ($#argv != 3) then
  echo "Usage:  $0 states symbols init"
  exit 1
endif

set states=$argv[1]
set symbols=$argv[2]
set init=$argv[3]

set example_string="${states}x${symbols}/${init}"

while (1)
  echo ""
  echo 'date; echo "Number of steps attained: $(./merge_steps_examples.py data/'${example_string}'/steps_* | wc -l)"' | /bin/bash
  sleep 10
end
