#!/bin/csh -f
set update_cmd="update"

set argc=$#argv
if ("${argc}" >= 1) then
  set basename="$1"
else
  echo "Usage:  assign_undecided basename [update_cmd]"
  exit 1
endif
if ("${argc}" >= 2) then
  set update_cmd="$2"
endif

set num_undecided=`ls -s ${basename}.undecided | awk '{print $1;}'`
while (${num_undecided} != 0)
  echo "----- Undecided -----"
  time ${update_cmd} "${basename}" Assign_Undecideds_Filter --next_machine_number=0

  set num_undecided=`ls -s ${basename}.undecided | awk '{print $1;}'`
end

exit 0
