#!/bin/csh -f
####
# Check for enough arguments
set argc="$#argv"
if ("$argc" < 2) then
  echo "Usage: cull_recur ref_file recur_file"
  exit 1
endif

set cmd_dir=`dirname $0`
set tmp_file="/tmp/cull_recur$$"

set ref_file="$argv[1]"
set recur_file="$argv[2]"

set width=`head -1 ${ref_file} | awk -f ${cmd_dir}/cull_recur2.awk`

cat ${ref_file}                                 | sed -e 's/|.*$//' >  ${tmp_file}
awk -f ${cmd_dir}/cull_recur1.awk ${recur_file} | sed -e 's/|.*$//' >> ${tmp_file}

sort -o ${tmp_file} ${tmp_file}
uniq -u ${tmp_file}

/bin/rm ${tmp_file}
