#!/bin/tcsh -f

set cmd_dir=`dirname $0`
set filter_dir=${cmd_dir}/../Code

setenv PATH ${PATH}:${cmd_dir}:${filter_dir}

echo ""
grep Halt $* | awk '{print $NF;}' | sort -n | uniq | lazy_beaver.py
echo ""
grep Unknown $* | awk '{print $NF;}' | sort -n | head -5
echo ""
