#!/bin/tcsh -f

set cmd_dir=`dirname $0`
set filter_dir=${cmd_dir}/../Code

setenv PATH ${PATH}:${cmd_dir}:${filter_dir}

if ($#argv < 1) then
  echo "Usage: `basename $0` [--nprocs=#] basename"
  exit 1
endif

set nprocs=`run_preprocessor $argv[1]`
if ($status == 0) then
  shift argv
endif

if ($#argv < 1) then
  echo "Usage: `basename $0` [--nprocs=#] basename"
  exit 1
endif

set basename=$1

if (${nprocs} == 1) then
  set update_cmd="update"
else
  set update_cmd="update_parallel ${nprocs}"
endif

echo "----- Reverse -----"
time ${update_cmd} ${basename} "f" Reverse_Engineer_Filter.py

set time=0.001

run_macro_simulator_filter "${basename}" 100 1 6 ${time} "${update_cmd}"

echo "----- Reverse -----"
time ${update_cmd} ${basename} "f" Reverse_Engineer_Filter.py

set time=0.01

foreach size (1 2)
  foreach ctl (1 2 3 4)
    set offset=0
    while (${offset} < ${size})
      echo "----- CTL${ctl} ${size} ${offset} ${time} -----"
      time ${update_cmd} ${basename} "f" CTL_Filter.py --time=${time} --type=CTL${ctl} --block-size=${size} --offset=${offset}
      @ offset++
    end  
  end
end

assign_undecided "${basename}" "${update_cmd}"

run_macro_simulator_filter "${basename}" 1000 1 8 ${time} "${update_cmd}"

set time=0.1

foreach size (1 2 3)
  foreach ctl (1 2 3 4)
    set offset=0
    while (${offset} < ${size})
      echo "----- CTL${ctl} ${size} ${offset} ${time} -----"
      time ${update_cmd} ${basename} "f" CTL_Filter.py --time=${time} --type=CTL${ctl} --block-size=${size} --offset=${offset}
      @ offset++
    end  
  end
end

run_macro_simulator_filter "${basename}" 10000 1 8 ${time} "${update_cmd}"

foreach size (4 5 6)
  foreach ctl (1 2 3 4)
    set offset=0
    while (${offset} < ${size})
      echo "----- CTL${ctl} ${size} ${offset} ${time} -----"
      time ${update_cmd} ${basename} "f" CTL_Filter.py --time=${time} --type=CTL${ctl} --block-size=${size} --offset=${offset}
      @ offset++
    end  
  end
end

assign_undecided "${basename}" "${update_cmd}"

run_macro_simulator_filter "${basename}" 10000 9 25 ${time} "${update_cmd}"
