#!/bin/tcsh -f

set cmd_dir=`dirname $0`
set filter_dir=${cmd_dir}/../busybeaver

setenv PATH ${PATH}:${cmd_dir}:${filter_dir}

set basename=$1

set update_cmd="update"

set time=1.0
# set time=10.0

foreach size (1 2 3 4 5 6)
  foreach ctl (1 2 3 4)
    set offset=0
    while (${offset} < ${size})
      echo "----- CTL${ctl} ${size} ${offset} ${time} -----"
      time ${update_cmd} ${basename} CTL_Filter.py --time=${time} --type=CTL${ctl} --size=${size} --offset=${offset}
      @ offset++
    end  
  end
end
