#!/bin/tcsh -f

set cmd_dir=`dirname $0`
set filter_dir=${cmd_dir}/../Code

setenv PATH ${PATH}:${cmd_dir}:${filter_dir}

set nprocs=1

set args=`getopt -u -l nprocs: "" $argv[1]`

if ($status != 0) then
  echo "Usage: `basename $0` [--nprocs=#] basename <enumerate-options>"
  exit 1
endif

while (1)
  if ($#args < 1) then
    echo "Usage: `basename $0` [--nprocs=#] basename <enumerate-options>"
    exit 1
  endif
  switch ($args[1])
    case "--nprocs":
      shift args
      set nprocs=$args[1]
      shift args
      shift argv
      breaksw

    case "--":
      break
      breaksw
  endsw
end

if ($#argv < 1) then
  echo "Usage: `basename $0` [--nprocs=#] basename <enumerate-options>"
  exit 1
endif

set basename=$1

echo "----- Enumerate -----"
if (${nprocs} == 1) then
  time update ${basename} "g" Enumerate.py $argv[2-]
else
  time update ${basename} "g" Enumerate_Filter_Parallel $nprocs $basename $argv[2-]
endif
