#!/bin/tcsh -f

set cmd_dir=`dirname $0`
set filter_dir=${cmd_dir}/../Code

setenv PATH ${PATH}:${cmd_dir}:${filter_dir}

set nprocs=`run_preprocessor $argv[1]`
if ($status == 0) then
  shift argv
endif

if ($#argv < 1) then
  echo "Usage: `basename $0` [--nprocs=#] basename"
  exit 1
endif

set basename=$1

if (${nprocs} == 1) then
  set update_cmd="update"
else
  set update_cmd="update_parallel ${nprocs}"
endif

# set time=0.001
# set time=0.01
# set time=0.1
set time=1.0
# set time=10.0

run_macro_simulator_filter "${basename}" 1000000000000000000 1 25 ${time} "${update_cmd}"
