#!/bin/tcsh -f

set cmd_dir=`dirname $0`
set filter_dir=${cmd_dir}/../Code

setenv PATH ${PATH}:${cmd_dir}:${filter_dir}

set nprocs=1

set args=`getopt -u -l nprocs: "" $argv[1]`

if ($status != 0) then
  echo "Usage: `basename $0` [--nprocs=#] basename"
  exit 1
endif

while (1)
  if ($#args < 1) then
    echo "Usage: `basename $0` [--nprocs=#] basename"
    exit 1
  endif
  switch ($args[1])
    case "--nprocs":
      shift args
      set nprocs=$args[1]
      shift args
      shift argv
      breaksw

    case "--":
      break
      breaksw
  endsw
end

if ($#argv < 1) then
  echo "Usage: `basename $0` [--nprocs=#] basename"
  exit 1
endif

set basename=$1

if (${nprocs} == 1) then
  set update_cmd="update"
else
  set update_cmd="update_parallel ${nprocs}"
endif

echo "----- Dual -----"
time ${update_cmd} ${basename} "g" Dual_Machine_Filter.py --tape=100 --steps=100

set num_undecided=`ls -s ${basename}.undecided | awk '{print $1;}'`

while ($num_undecided != 0)
  echo "----- Undecided/Dual -----"
  time ${update_cmd} ${basename} "g" Find_New_TM_Filter --tape=100 --steps=100 --next_machine_number=0

  set num_undecided=`ls -s ${basename}.undecided | awk '{print $1;}'`
end
