#!/bin/tcsh -f

set cmd_dir=`dirname $0`
set filter_dir=${cmd_dir}/../Code

setenv PATH ${PATH}:${cmd_dir}:${filter_dir}

set nprocs=$1
set basename=$2
set cmd_file=$3

set update_cmd="update_parallel ${nprocs}"

echo "----- Integrate -----"
time update ${basename} "f" Initial_Filter

# echo "----- Dual -----"
# time ${update_cmd} ${basename} "f" Dual_Machine_Filter.py --tape=100 --steps=100
# 
# set num_undecided=`ls -s ${basename}.undecided | awk '{print $1;}'`
# 
# while ($num_undecided != 0)
#   echo "----- Undecided/Dual -----"
#   time ${update_cmd} ${basename} "f" Find_New_TM_Filter --tape=100 --steps=100 --next_machine_number=0
# 
#   set num_undecided=`ls -s ${basename}.undecided | awk '{print $1;}'`
# end

set num_lines=`cat $cmd_file | wc -l`
set line=1
while ($line <= $num_lines)
  set cur_cmd=`head -$line $cmd_file | tail -1`
  echo "----- $cur_cmd -----"
  time $update_cmd $basename "f" $cur_cmd

  if (`expr $line % 5` == 0) then
    set cur_cmd='Assign_Undecideds_Filter --next_machine_number=0'
    echo "----- $cur_cmd -----"
    time $update_cmd $basename "f" $cur_cmd
  endif

  @ line++
end
