#!/bin/tcsh -f

set cmd_dir=`dirname $0`
set filter_dir=${cmd_dir}/../Code

setenv PATH ${PATH}:${cmd_dir}:${filter_dir}

if ($#argv < 1) then
  echo "Usage `basename $0` basename"
  exit 1
endif

set basename=$1

set update_cmd="update"

set time=1.0
# set time=10.0

foreach size (1 2 3 4 5 6)
  foreach ctl (1 2 3 4)
    set offset=0
    while (${offset} < ${size})
      echo "----- CTL${ctl} ${size} ${offset} ${time} -----"
      time ${update_cmd} ${basename} "f" CTL_Filter.py --time=${time} --type=CTL${ctl} --block-size=${size} --offset=${offset}
      @ offset++
    end  
  end
end
