#!/bin/tcsh -f

set cmd_dir=`dirname $0`
set filter_dir=${cmd_dir}/../Code

setenv PATH ${PATH}:${cmd_dir}:${filter_dir}

if ($#argv < 1) then
  echo "Usage `basename $0` nprocs basename"
  exit 1
endif

set nprocs=$1
set basename=$2

set update_cmd="update_parallel ${nprocs}"

set time=1.0
# set time=10.0

foreach size (7 8 9 10 11 12)
  foreach ctl (1 2 3 4)
    set offset=0
    while (${offset} < ${size})
      echo "----- CTL${ctl} ${size} ${offset} ${time} -----"
      time ${update_cmd} ${basename} "f" CTL_Filter.py --time=${time} --type=CTL${ctl} --block-size=${size} --offset=${offset}
      @ offset++
    end  
  end
end
