#!/bin/tcsh -f

set cmd_dir=`dirname $0`
set filter_dir=${cmd_dir}/../Code

setenv PATH ${PATH}:${cmd_dir}:${filter_dir}

if ($#argv < 2) then
  echo "Usage `basename $0` basename cmd_file"
  exit 1
endif

set basename=$1
set cmd_file=$2

set update_cmd="update"

set num_lines=`cat $cmd_file | wc -l`
set line=1
while ($line <= $num_lines)
  set cur_cmd=`head -$line $cmd_file | tail -1`
  echo "----- $cur_cmd -----"
  time $update_cmd $basename "f" $cur_cmd

  if (`expr $line % 5` == 0) then
    set cur_cmd='Assign_Undecideds_Filter --next_machine_number=0'
    echo "----- $cur_cmd -----"
    time $update_cmd $basename "f" $cur_cmd
  endif

  @ line++
end
