#!/bin/csh -f
set tape=1000
set steps=1000
set size=1
set stop=10000

set nprocs=`run_preprocessor $argv[1]`
if ($status == 0) then
  shift argv
endif

set argc=$#argv
if ("$argc" >= 1) then
  set base="$1"
else
  echo "Usage: `basename $0` [--nprocs=#] basename [tape [steps [start_size [stop_size]]]]"
  exit 1
endif
if ("$argc" >= 2) then
  set tape="$2"
endif
if ("$argc" >= 3) then
  set steps="$3"
endif
if ("$argc" >= 4) then
  set size="$4"
endif
if ("$argc" >= 5) then
  set stop="$5"
endif

if (${nprocs} == 1) then
  set update_cmd="update"
else
  set update_cmd="update_parallel ${nprocs}"
endif

wc -l "$base".unknown
echo ""
while ("$size" <= "$stop")
  echo $size
  set cur_steps=`expr $steps \* $size`
  set cur_tape=`expr $tape \* $size`
  ${update_cmd} "$base" "f" Macro_Machine_Filter.py --tape=$cur_tape --steps=$cur_steps --block-size=$size
  wc -l "$base".unknown
  if (-e "$base".error) then
    echo "Error encountered..."
    exit 1
  endif
  echo ""
  @ size++
end
exit 0
