#!/bin/tcsh -f

set cmd_dir=`dirname $0`
set filter_dir=${cmd_dir}/../busybeaver

setenv PATH ${PATH}:${cmd_dir}:${filter_dir}

set nprocs=$1
set basename=$2

set update_cmd="update_parallel ${nprocs}"

# set time=0.001
# set time=0.01
# set time=0.1
set time=1.0
# set time=10.0

run_macro_simulator_filter "${basename}" 1000000000000000000 1 25 ${time} "${update_cmd}"
