#!/bin/tcsh -f

set cmd_dir=`dirname $0`
set filter_dir=${cmd_dir}/../Code

setenv PATH ${PATH}:${cmd_dir}:${filter_dir}

set nprocs=1

set args=`getopt -u -l nprocs: "" $argv[1]`

if ($status != 0) then
  echo "Usage: `basename $0` [--nprocs=#] basename"
  exit 1
endif

while (1)
  if ($#args < 1) then
    echo "Usage: `basename $0` [--nprocs=#] basename"
    exit 1
  endif
  switch ($args[1])
    case "--nprocs":
      shift args
      set nprocs=$args[1]
      shift args
      shift argv
      breaksw

    case "--":
      break
      breaksw
  endsw
end

if ($#argv < 1) then
  echo "Usage: `basename $0` [--nprocs=#] basename"
  exit 1
endif

set basename=$1

if (${nprocs} == 1) then
  set update_cmd="update"
else
  set update_cmd="update_parallel ${nprocs}"
endif

set time=1.0
# set time=10.0

foreach size (1 2 3 4 5 6)
  foreach ctl (1 2 3 4)
    set offset=0
    while (${offset} < ${size})
      echo "----- CTL${ctl} ${size} ${offset} ${time} -----"
      time ${update_cmd} ${basename} "f" CTL_Filter.py --time=${time} --type=CTL${ctl} --block-size=${size} --offset=${offset}
      @ offset++
    end  
  end
end
