#!/bin/tcsh -f

set cmd_dir=`dirname $0`
set filter_dir=${cmd_dir}/../busybeaver

setenv PATH ${PATH}:${cmd_dir}:${filter_dir}

set basename=$1

set update_cmd="update"

# set time=0.001
# run_macro_simulator_filter "${basename}" 1000000000000000000 1 6 ${time} "${update_cmd}"

# set time=0.01
# run_macro_simulator_filter "${basename}" 1000000000000000000 1 8 ${time} "${update_cmd}"

# set time=0.1
# run_macro_simulator_filter "${basename}" 1000000000000000000 1 25 ${time} "${update_cmd}"

# set time=1.0
# run_macro_simulator_filter "${basename}" 1000000000000000000 1 25 ${time} "${update_cmd}"

set time=10.0
run_macro_simulator_filter "${basename}" 1000000000000000000 1 25 ${time} "${update_cmd}"
