#!/bin/csh -f
set steps=1000
set tape=1000

set size=1
set stop=10000

set argc=$#argv
if ("$argc" >= 2) then
  set nprocs="$1"
  set base="$2"
else
  echo "Usage:  run_macro_machine_filter_parallel nprocs basename [tape [steps [start_size [stop_size]]]]"
  exit 1
endif
if ("$argc" >= 2) then
  set tape="$2"
endif
if ("$argc" >= 3) then
  set steps="$3"
endif
if ("$argc" >= 4) then
  set size="$4"
endif
if ("$argc" >= 5) then
  set stop="$5"
endif

wc -l "$base".unknown
echo ""
while ("$size" <= "$stop")
  echo $size
  set cur_steps=`expr $steps \* $size`
  set cur_tape=`expr $tape \* $size`
  update_parallel "$nprocs" "$base" "f" Macro_Machine_Filter.py --tape=$cur_tape --steps=$cur_steps --block-size=$size
  wc -l "$base".unknown
  if (-e "$base".error) then
    echo "Error encountered..."
    exit 1
  endif
  echo ""
  @ size++
end
exit 0
