#!/bin/csh -f
set exit_code=1
set nprocs=1

if (${#argv} > 0) then
  echo ${argv} | grep '^--nprocs=[0-9][0-9]*' >& /dev/null

  if (${status} == 0) then
    set nprocs=`echo ${argv} | sed -e 's/^--nprocs=//'`
    set exit_code=0
  endif
endif

echo ${nprocs}
exit ${exit_code}
