#!/bin/tcsh -f

set cmd_dir=`dirname $0`
set filter_dir=${cmd_dir}/../Code

setenv PATH ${PATH}:${cmd_dir}:${filter_dir}

if ($#argv < 1) then
  echo "Usage: `basename $0` [--nprocs=#] basename <enumerate-options>"
  exit 1
endif

set nprocs=`run_preprocessor $argv[1]`
if ($status == 0) then
  shift argv
endif

if ($#argv < 1) then
  echo "Usage: `basename $0` [--nprocs=#] basename <enumerate-options>"
  exit 1
endif

set basename=$1

set enumerate=`which Enumerate.py`

echo "----- Enumerate -----"
if (${nprocs} == 1) then
  time update ${basename} "g" ${enumerate} $argv[2-]
else
  if (-e machinefile) then
    time update ${basename} "g" mpirun -np $nprocs -machinefile machinefile ${enumerate} $argv[2-]
  else
    time update ${basename} "g" mpirun -np $nprocs ${enumerate} $argv[2-]
  endif
endif
