#!/bin/tcsh -f

set cmd_dir=`dirname $0`
set filter_dir=${cmd_dir}/../Code

setenv PATH ${PATH}:${cmd_dir}:${filter_dir}

if ($#argv < 1) then
  echo "Usage `basename $0` basename"
  exit 1
endif

set basename=$1

set update_cmd="update"

echo "----- Dual -----"
time ${update_cmd} ${basename} "g" Dual_Machine_Filter.py --tape=100 --steps=100

set num_undecided=`ls -s ${basename}.undecided | awk '{print $1;}'`

while ($num_undecided != 0)
  echo "----- Undecided/Dual -----"
  time ${update_cmd} ${basename} "g" Find_New_TM_Filter --tape=100 --steps=100 --next_machine_number=0

  set num_undecided=`ls -s ${basename}.undecided | awk '{print $1;}'`
end
