#!/bin/tcsh -f

set cmd_dir=`dirname $0`
set filter_dir=${cmd_dir}/../Code

setenv PATH ${PATH}:${cmd_dir}:${filter_dir}

set nprocs=$1
set basename=$2

set update_cmd="update_parallel ${nprocs}"

set time=1.0
# set time=10.0

foreach size (1 2 3 4 5 6)
  foreach ctl (1 2 3 4)
    set offset=0
    while (${offset} < ${size})
      echo "----- CTL${ctl} ${size} ${offset} ${time} -----"
      time ${update_cmd} ${basename} "f" CTL_Filter.py --time=${time} --type=CTL${ctl} --size=${size} --offset=${offset}
      @ offset++
    end  
  end
end
